import oracledb
import os
from dotenv import load_dotenv
load_dotenv()

username = os.getenv("ORACLE_USER")
dsn = os.getenv("ORACLE_DSN")
password = os.getenv("ORACLE_PASSWORD")


def get_connection():
    return oracledb.connect(user=username, password=password, dsn=dsn)


def create_schema(query):
    try:
        with get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute(query)
                print(f"Tabla creada \n {query}")
    except oracledb.DatabaseError as error:
        print(f"No se pudo crear la tabla: {error}")

tables = [

    (
        "CREATE TABLE Cliente ("
        "correo_electronico VARCHAR(80) PRIMARY KEY,"
        "nombre_Cliente VARCHAR(50),"
        "telefono VARCHAR(12)"
        ")"
    ),

    (
        "CREATE TABLE Pedido ("
        "numero_Pedido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        "fecha_Pedido VARCHAR(20),"
        "total NUMBER,"
        "datos_Cliente VARCHAR(80),"
        "FOREIGN KEY (datos_Cliente) REFERENCES Cliente(correo_electronico)"
        ")"
    ),

     (
        "CREATE TABLE Pedido_Local ("
        "numero_Pedido NUMBER PRIMARY KEY,"
        "n_Mesa NUMBER,"
        "FOREIGN KEY (numero_Pedido) REFERENCES Pedido(numero_Pedido)"
        ")"
    ),

    (
        "CREATE TABLE Pedido_Llevar ("
        "numero_Pedido NUMBER PRIMARY KEY,"
        "Tiempo_Retiro VARCHAR2(20),"
        "FOREIGN KEY (numero_Pedido) REFERENCES Pedido(numero_Pedido)"
        ")"
    )
    
    (
         "CREATE TABLE Pedido_Domicilio ("
        "numero_Pedido NUMBER PRIMARY KEY,"
        "direccion VARCHAR2(100),"
        "nombre_Repartidor VARCHAR2(50),"
        "FOREIGN KEY (numero_Pedido) REFERENCES Pedido(numero_Pedido)"
        ")"
    )


]

for query in tables:
    create_schema(query)

def create_Cliente(
        correo: str,
        nombre: str,
        telefono: str,
):
    sql = (

        "INSERT INTO"
    )
def create_Pedido(
        fecha: str,
        total: int,
        datos_Cliente: str,
):
    pass
def create_Pedido_Local(
        numero_Pedido: int,
        n_Mesa: int,
):
    pass
def create_Pedido_Llevar(
        numero_Pedido: int,
        tiempo_Retiro: str,
):
    pass
def create_Pedido_Domicilio(
        numero_Pedido: int,
        direccion: str,
        nombre_Repartidor: str,
):
    pass

def read_Cliente():
    sql = (
        "SELECT * FROM Cliente"
    )
    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                resultados = cur.execute(sql)
                print(f"Consulta a la tabla Cliente")
                for fila in resultados:
                    print(fila)
    except oracledb.DatabaseError as e:
        err = e
        print(f"Error al insertar datos: {err}")                

def read_Pedido(id):
    sql = (
        "SELECT * FROM Pedido WHERE id = :id"
    )

    parametros = {"id": id}

    try:
        with get_connection() as conn:
            with conn.cursor() as cur:
                resultados = cur.execute(sql,parametros)
                print(f"Consulta la tabla Pedido por ID")
                for fila in resultados:
                    print(fila)
    except oracledb.DatabaseError as e:
        err = e
        print(f"Error al insertar datos: {err}")
def read_Pedido_Local():
    pass
def read_Pedido_Llevar():
    pass
def read_Pedido_Domicilio():
    pass



#UPDTADE

from typing import Optional
def update_cliente(correo_electronico, nombre, telefono):
    modificaciones = []
    parametros = {"correo_electronico": correo_electronico}

    if correo_electronico  is not None:
        modificaciones.append("correo_electronico =: correo_electronico ")
        parametros["correo_electronico"] = correo_electronico
    if nombre is not None:
        modificaciones.append("nombre =: nombre")
        parametros["nombre"] = nombre
    if telefono is not None:
        modificaciones.append("telefono =: telefono")
        parametros["telefono"] = telefono
    if not modificaciones:
        return print("No hay campos para actualizar.")
   
    sql = f"UPDATE cliente SET {", ".join(modificaciones)} WHERE correo_electronico =: correo_electronico"
    print(sql)
    with get_connection() as conn:
            with conn.cursor() as cur:
                resultados = cur.execute(sql)
            conn.commit()
            print(f"Cliente con correo_electronico= {correo_electronico} actualizada.")



#delete - eliminacion de datos
def delete_Cliente (correo_electronico : str):
    sql = (
        "DELETE FROMPERSONAS WHERE correo_electronico = :correo_electronico"

    )

    parametros= {"correo_electronico" : correo_electronico}
    try:
        with get_connection () as conn:
            with conn.cursor () as cur:
                cur.execute(sql, parametros)
            conn.commit()
            print(f"Dato eliminado \n {parametros}")
    except oracledb.DatabaseError as e:
        err= e 
        print(f"Error al eliminar dato: {err} \n {sql} \ {parametros}")

def main():
    while True:
        print(
            """

            ======================================
            |   CRUD CON ORACLESQL                |
            ======================================
            |1.aplicar esquema en la base de datos|
            |2.tabla Clientes                     |
            |3.tabla Pedidos                      |
            |4.tabla Pedido_Local                 |
            |5.tabla Pedido_Llevar                |
            |6.Pedido_Domicilio                    |
            |0. salir                             |
            =======================================
            """
        )
        opcion = input("selecciona una opcion [1-4, 0 para salir]:")

        if opcion == "0":
            print("Adios")
            input("Presiona ENTER para continuar...")
            break
        elif opcion == "1":
            pass
        elif opcion == "2":
            pass
        elif opcion == "3":
            pass
        elif opcion == "4":
            pass
        else:
if __name__=="__main__":
    main() 
