import oracledb
import os
from dotenv import load_dotenv
load_dotenv()

username = os.getenv("ORACLE_USER")
dsn = os.getenv("ORACLE_DSN")
password = os.getenv("ORACLE_PASSWORD")


def get_connection():
    return oracledb.connect(user=username, password=password, dsn=dsn)


def create_schema(query):
    try:
        with get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute(query)
                print(f"Tabla creada \n {query}")
    except oracledb.DatabaseError as error:
        print(f"No se pudo crear la tabla: {error}")

tables = [

    (
        "CREATE TABLE Cliente ("
        "correo_electronico VARCHAR(80) PRIMARY KEY,"
        "nombre_Cliente VARCHAR(50),"
        "telefono VARCHAR(12)"
        ")"
    ),

    (
        "CREATE TABLE Pedido ("
        "numero_Pedido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        "fecha_Pedido VARCHAR(20),"
        "total NUMBER,"
        "datos_Cliente VARCHAR(80),"
        "FOREIGN KEY (datos_Cliente) REFERENCES Cliente(correo_electronico)"
        ")"
    ),

     (
        "CREATE TABLE Pedido_Local ("
        "numero_Pedido NUMBER PRIMARY KEY,"
        "n_Mesa NUMBER,"
        "FOREIGN KEY (numero_Pedido) REFERENCES Pedido(numero_Pedido)"
        ")"
    ),

    (
        "CREATE TABLE Pedido_Llevar ("
        "numero_Pedido NUMBER PRIMARY KEY,"
        "Tiempo_Retiro VARCHAR2(20),"
        "FOREIGN KEY (numero_Pedido) REFERENCES Pedido(numero_Pedido)"
        ")"
    )
    
    (
         "CREATE TABLE Pedido_Domicilio ("
        "numero_Pedido NUMBER PRIMARY KEY,"
        "direccion VARCHAR2(100),"
        "nombre_Repartidor VARCHAR2(50),"
        "FOREIGN KEY (numero_Pedido) REFERENCES Pedido(numero_Pedido)"
        ")"
    )


]

for query in tables:
    create_schema(query)


